# Perform various operations on the building block of PyTorch : Tensors

# Pytorch: Tensors

---



### Contents:
1. Create tensor
2. Tensor attributes
3. Arithmetic operations
4. Trigonometric operations
5. Functions using tensors
6. Gradients


---



- Type and Size: Each tensor has an associated type and size. The default tensor type when you use
the torch.Tensor constructor is torch.FloatTensor. However, you can convert a tensor to a
different type (float, long, double, etc.) by specifying it at initialization or later using one of the
typecasting methods.
### Three attributes which uniquely define a tensor are:
- dtype: What is actually stored in each element of the tensor? This could be floats or integers etc.
- PyTorch has nine different data types.
- layout: How we logically interpret this physical memory. The most common layout is a strided
tensor. Strides are a list of integers: the k-th stride represents the jump in the memory necessary to
go from one element to the next one in the k-th dimension of the Tensor.
- device: Where the tensor's physical memory is actually stored, e.g., on a CPU, or a GPU.
The torch.device contains a device type ('cpu' or 'cuda') and optional device ordinal for the device
type

### 0. Import required libraries and prepare data

In [ ]:
!pip install torch -q
!pip install pandas -q

In [ ]:
import torch
import pandas as pd

### 1. create tensors

#### 1-D tensor

In [ ]:
# one dimensional tensor
x_list = [1,2,3]
x = torch.tensor(x_list)
print(x)

tensor([1, 2, 3])


#### attributes of a tensor

In [ ]:
# shape
print('tenosr shape: ',x.shape)

tenosr shape:  torch.Size([3])


In [ ]:
# data type
print('tensor data type: ',x.dtype)

tensor data type:  torch.int64


In [ ]:
# device for operation
print('tensor operations on device: ',x.device)

tensor operations on device:  cpu


#### 2-D tensor (also called matrix)

In [ ]:
x_list = [[1,2,3],[4,5,6]]
x = torch.tensor(x_list)

# tensor attributes
# shape
print('tenosr shape: ',x.shape)
# data type
print('tensor data type: ',x.dtype)
# device for operation
print('tensor operations on device: ',x.device)

tenosr shape:  torch.Size([2, 3])
tensor data type:  torch.int64
tensor operations on device:  cpu


#### 3-D Tensor

In [ ]:
# three dimensional array: tensor (>=3 dimensions)
x_list = [[[1],[2]],[[3], [4]],[[5],[6]]]
x = torch.tensor(x_list)

# shape
print('tenosr shape: ',x.shape)
# data type
print('tensor data type: ',x.dtype)
# device for operation
print('tensor operations on device: ',x.device)

tenosr shape:  torch.Size([3, 2, 1])
tensor data type:  torch.int64
tensor operations on device:  cpu


#### empty tensor

In [ ]:
# create empty tensor
x = torch.ones((6))
print('empty tensor \n', x)


empty tensor 
 tensor([1., 1., 1., 1., 1., 1.])


In [ ]:
# modify tensor through indexing and assignment
for i in range(6):
    x[i] = x[i]+3

print('modified tensor \n', x)

modified tensor 
 tensor([4., 4., 4., 4., 4., 4.])


## Creating tensors from Dataset

In [ ]:
#%% convert features of a dataset into tensor
data_path = "../Input"
# read dataset stored as csv using pandas
file_path = data_path + '/churn_data.csv'
file_path =  '/content/churn_data.csv'
# read csv file
df = pd.read_csv(file_path)
# features of the dataset
columns_names = df.columns.values
print('The dataset has {} attributes : \n {}'.format(len(columns_names), columns_names))


The dataset has 16 attributes : 
 ['year' 'customer_id' 'phone_no' 'gender' 'age' 'no_of_days_subscribed'
 'multi_screen' 'mail_subscribed' 'weekly_mins_watched'
 'minimum_daily_mins' 'maximum_daily_mins' 'weekly_max_night_mins'
 'videos_watched' 'maximum_days_inactive' 'customer_support_calls' 'churn']


In [ ]:
df.shape

(2000, 16)

In [ ]:
df.head()

year  customer_id  phone_no  gender  age  no_of_days_subscribed  \
0  2015       100198  409-8743  Female   36                     62   
1  2015       100643  340-5930  Female   39                    149   
2  2015       100756  372-3750  Female   65                    126   
3  2015       101595  331-4902  Female   24                    131   
4  2015       101653  351-8398  Female   40                    191   

  multi_screen mail_subscribed  weekly_mins_watched  minimum_daily_mins  \
0           no              no               148.35                12.2   
1           no              no               294.45                 7.7   
2           no              no                87.30                11.9   
3           no             yes               321.30                 9.5   
4           no              no               243.00                10.9   

   maximum_daily_mins  weekly_max_night_mins  videos_watched  \
0               16.81                     82               1   
1               33.37                     87               3   
2                9.89                     91               1   
3               36.41                    102               4   
4               27.54                     83               7   

   maximum_days_inactive  customer_support_calls  churn  
0                    4.0                       1    0.0  
1                    3.0                       2    0.0  
2                    4.0                       5    1.0  
3                    3.0                       3    0.0  
4                    3.0                       1    0.0

In [ ]:
# create tensor using the weekly_mins_watched feature in the dataset
x = torch.tensor(df[['weekly_mins_watched', 'minimum_daily_mins',"maximum_daily_mins"]].values)

In [ ]:
# tensor shape
x.shape

torch.Size([2000, 3])

In [ ]:
x.dtype

torch.float64

In [ ]:
x

tensor([[148.3500,  12.2000,  16.8100],
        [294.4500,   7.7000,  33.3700],
        [ 87.3000,  11.9000,   9.8900],
        ...,
        [128.8500,  15.6000,  14.6000],
        [178.0500,  10.4000,  20.1800],
        [326.7000,  10.3000,  37.0300]], dtype=torch.float64)

## Arithmetic operations

Pytorch allows you to perform arithmetic operations on tensors. In this
chapter of Pytorch tutorial, you will learn how to do arithmetic operations of Pytorch tensors.
These operations can be performed by using pytorch arithmetic operation
functions or python operands.
## The arithmetic operations are performed element-wise.
- Addition
- Subtraction
- Multiplication
- Division
- Exponent

### Add and Subtract

In [ ]:
# add
x2 = torch.add(x,x)
print(x2)
print('x2 shape: {} \n'.format(x2.shape))


tensor([[296.7000,  24.4000,  33.6200],
        [588.9000,  15.4000,  66.7400],
        [174.6000,  23.8000,  19.7800],
        ...,
        [257.7000,  31.2000,  29.2000],
        [356.1000,  20.8000,  40.3600],
        [653.4000,  20.6000,  74.0600]], dtype=torch.float64)
x2 shape: torch.Size([2000, 3]) 



In [ ]:
x2 = x + x
print(x2)
print('x2 shape: {}'.format(x2.shape))

tensor([[296.7000,  24.4000,  33.6200],
        [588.9000,  15.4000,  66.7400],
        [174.6000,  23.8000,  19.7800],
        ...,
        [257.7000,  31.2000,  29.2000],
        [356.1000,  20.8000,  40.3600],
        [653.4000,  20.6000,  74.0600]], dtype=torch.float64)
x2 shape: torch.Size([2000, 3])


In [ ]:
# subtract
x_2 = torch.subtract(x,x)
print(x_2)
print('x_2 shape: {} \n'.format(x_2.shape))

x_2 = x - 2 * x
print(x_2)
print('x_2 shape: {}'.format(x_2.shape))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
x_2 shape: torch.Size([2000, 3]) 

tensor([[-148.3500,  -12.2000,  -16.8100],
        [-294.4500,   -7.7000,  -33.3700],
        [ -87.3000,  -11.9000,   -9.8900],
        ...,
        [-128.8500,  -15.6000,  -14.6000],
        [-178.0500,  -10.4000,  -20.1800],
        [-326.7000,  -10.3000,  -37.0300]], dtype=torch.float64)
x_2 shape: torch.Size([2000, 3])


### Multiply

In [ ]:
# element wise multiplication
x_mult = x[0:5,:] * x[0:5,:]
print(x_mult.shape)

torch.Size([5, 3])


In [ ]:
x_mult

tensor([[2.2008e+04, 1.4884e+02, 2.8258e+02],
        [8.6701e+04, 5.9290e+01, 1.1136e+03],
        [7.6213e+03, 1.4161e+02, 9.7812e+01],
        [1.0323e+05, 9.0250e+01, 1.3257e+03],
        [5.9049e+04, 1.1881e+02, 7.5845e+02]], dtype=torch.float64)

In [ ]:
# matrix multiplication of sliced tensor with transpose of it
x_matmult = x[0:5,:] @ x[0:5,:].T
print(x_matmult.shape)
# 5 X 3 | 3 X 5 = 5 x 5

torch.Size([5, 5])


In [ ]:
x_matmult

tensor([[ 22439.1386,  44336.5472,  13262.3859,  48392.8071,  36644.9774],
        [ 44336.5472,  87873.6494,  26127.1443,  95894.9367,  72554.2898],
        [ 13262.3859,  26127.1443,   7860.7121,  28522.6349,  21615.9806],
        [ 48392.8071,  95894.9367,  28522.6349, 104649.6281,  79182.1814],
        [ 36644.9774,  72554.2898,  21615.9806,  79182.1814,  59926.2616]],
       dtype=torch.float64)

### Trigonometric Operations

In [ ]:
#%% All trignonometric functions can be performed on tensors
# the values are considered in radians

x_cos = torch.cos(x[:5,:])
print(x_cos)


tensor([[-0.7680,  0.9336, -0.4518],
        [ 0.6527,  0.1534, -0.3740],
        [ 0.7872,  0.7861, -0.8937],
        [ 0.6543, -0.9972,  0.2780],
        [-0.4559, -0.0954, -0.7423]], dtype=torch.float64)


In [ ]:

x_sin = torch.sin(x[:5,:])
print(x_sin)


tensor([[-0.6405, -0.3582, -0.8921],
        [-0.7577,  0.9882,  0.9274],
        [-0.6167, -0.6181, -0.4486],
        [ 0.7562, -0.0752, -0.9606],
        [-0.8900, -0.9954,  0.6701]], dtype=torch.float64)


### Statistics

In [ ]:
#%% math operations for statistics

# calculate mean value of the number of weekly_mins_watched, minimum daily mins
x_mean = x.mean(dim=0)
print(x_mean)

tensor([270.1784,  10.1987,  30.6208], dtype=torch.float64)


In [ ]:
# calculate mean value of the number of weekly_mins_watched, minimum daily mins
x_median = x.median(dim=0)
print(x_median)

torch.return_types.median(
values=tensor([269.8500,  10.2000,  30.5800], dtype=torch.float64),
indices=tensor([ 263, 1157,  263]))


## Functions
tensors can be used to create functions

### Example 1:
$F(x)$ is a function of $x$  
$F(x) = x^2 + 2x + 1$

In [ ]:
### 1-D tensor
x = torch.ones((6))
print(x)

tensor([1., 1., 1., 1., 1., 1.])


In [ ]:
f = x**2 + 2*x + 1
print(f)

tensor([4., 4., 4., 4., 4., 4.])


In [ ]:
### 2-D tensor
x = torch.ones((3,2))
f = x**2 + 2*x + 1
print(f)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])


### Example 2:
$H(x)$ is a function of $F(x)$  
$H(x) = 3F(x) + 1$

In [ ]:
h = 3*f + 1
print(h)

tensor([[13., 13.],
        [13., 13.],
        [13., 13.]])


## Gradients
gradients are first order derivates of a function


### Example 1:
$F(x)$ is a function of $x$  
$F(x) = x^2 + 2x + 1$  

$G(x)$ is the gradient of $F(x)$ with respect to $x$  
$G(x) = \frac{dF(x)}{dx} = 2(x + 1)$  

In [ ]:
#%% gradients are first order derivates of a function

# create a tensor with gradient tracing enabled
# tensors should be of floating point type to calculate gradients
x = torch.tensor(5.0, requires_grad=True)

# define function
f = x**2 + 2*x + 1

# compute gradients
f.backward()

# print the gradient value
print(x.grad)


tensor(12.)


In [ ]:
#%% computing gradients with respect to a tensor

# create tensor using  'weekly_mins_watched', 'minimum_daily_mins' features in dataset
x = torch.tensor(df[['weekly_mins_watched', 'minimum_daily_mins']].values, requires_grad=True)

# calculate function of x
y = x**2 + 3

# calculate derivative of y with respect to x
y.backward(torch.ones_like(x))

# print x derviative values
print(x.grad)

tensor([[296.7000,  24.4000],
        [588.9000,  15.4000],
        [174.6000,  23.8000],
        ...,
        [257.7000,  31.2000],
        [356.1000,  20.8000],
        [653.4000,  20.6000]], dtype=torch.float64)


### Example 2:

$F(x)$ is a function of $x$  
$F(x) = x^2 + 2x + 1$  

$H(x)$ is a function of $F(x)$  
$H(x) = F^2(x) + 1$

$G(x)$ is the gradient of $H(x)$ with respect to $x$  
$G(x) = \frac{dH(x)}{dx} = 4(x + 1)^3$  

In [ ]:
x = torch.tensor(1.0, requires_grad=True)

# define functions
f = x**2 + 2*x + 1
h = f**2 + 1

# compute gradients
h.backward()

# print the gradient value
print(x.grad)

tensor(32.)


In [ ]:
# an exhaustive list of tensor features are available at: https://pytorch.org/docs/stable/torch.html